### ISSUE TITLE
Can not configure a project on windows

### ISSUE THREAD

**Issue by sbabbi** [mali/kdev-qmake#1]
Configuring a project on windows fails with message "No basic MkSpec file could be found for the given QMake binary".
Running kdevelop with the debug output you can see that all the environment variables returned by `QMakeConfig::queryQMake` contain a stray "\r" in the value. Checking in the code you can see that qmakeconfig.cpp:121 splits the lines using "\n", instead of "\r\n" (needs to be conditional for windows).

**Comment by mali** [comment]
hi sbabbi, here is just a copy of kdev-qmake, please use bugs.kde.org for reporting such issues.
Anyway, thank's for reporting this, I'll take care of it.
I'll close this clone for issues ;-)

**Comment by mali** [comment]
fixed by kevin funk !
see here : https://quickgit.kde.org/?p=kdevelop.git&a=commit&h=71cfc49efd6caaa2b2c7be4279d5d0cb52f1f38e
And fyi, kdev-qmake is now incorporated in kdevelop.
